"use client";
import "./globals.css";
import { useState, useEffect } from "react";
import Cabecalho from "@/componentes/cabecalho/page";
import Rodape from "@/componentes/rodape/page";
import SplashScreen from "../componentes/splashScreen/splashScreen";
import { usePathname } from "next/navigation";
import Image from "next/image";
import { path } from "animejs";

// export const metadata = {
//   title: "SmoakBook",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const pathname = usePathname();
  const isHome = pathname === "/usuarios/login";
  const [isLoading, setIsLoading] = useState(isHome);

  useEffect(() => {
    if (isLoading) return;
  }, [isLoading]);

  return (
    <html lang="pt-br">
      <head>
        <title>SmoakBook</title>
        <link rel="icon" href="/Icons TCC/favicon.ico" />
      </head>
      <body className="bg-white">
        {isLoading && isHome ? (
          <SplashScreen finishLoading={() => setIsLoading(false)} />
        ) : (
          <>
            <div className="layout">
              <Cabecalho />
              {children}
              <Rodape />
            </div>
          </>
        )}
      </body>
    </html>
  );
}
